:::{.callout-tip collapse="true" icon=false}
## Préparation de l'environnement de travail

:::{.incremental}
1. Créer un compte [`GitLab`](https://gitlab.com/)
2. Créer un nouveau dépôt **privé** sur `GitLab` dans son espace personnel
3. [Générer un *token*](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) (jeton d'authentification) sur `GitLab`
4. Créer un compte sur le [SSP Cloud](https://datalab.sspcloud.fr/home)
5. Stocker le *token GitLab* sur le `SSP Cloud` (ou un gestionnaire de mot de passe) :
    + `Mon Compte` -> `Services externes` -> `Jeton d'accès personnel GitHub` 
    + ⚠️ *La variable peut stocker un jeton GitHub ou GitLab au choix, malgré sa dénomination*
6. Lancer un service `RStudio`. Dans l'onglet de configuration `Git` du service, fixer la durée du `Cache` pour le stockage des identifiants `GitLab` à une valeur suffisamment élevée *(36000 = 10h)*
7. Cloner le dépôt distant sur votre environnement local (ici, le `RStudio` du `Datalab`):
    + `File` → `New project` → `Version Control` → `Git` en utilisant l'adresse https du repo
:::

:::

❓ **Question** : qu'est ce qui différencie le projet cloné d'un projet quelconque ?
